CC = gcc

CFLAGS  = -g -Wall $(shell pkg-config --cflags gtk+-2.0 webkit-1.0)

LDFLAGS = $(shell pkg-config --libs gtk+-2.0 webkit-1.0)

cwebkit:

.PHONY: clean
clean:
	rm -f *.o *~ *.swp *.swo a.out core cwebkit

.PHONY: all
all: clean cwebkit
